{{- if .Values.infra.kubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: infra-cluster-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  kubeconfig: |
{{ .Values.infra.kubeconfig | indent 4 }}
{{- end }}