apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-annotator-sa
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-annotator-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "patch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-annotator-binding
subjects:
  - kind: ServiceAccount
    name: node-annotator-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: node-annotator-role
  apiGroup: rbac.authorization.k8s.io