---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-csi-infra-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: kubevirt-csi-infra-token
  annotations:
    kubernetes.io/service-account.name: kubevirt-csi-infra-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevirt-csi-infra-role
rules:
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  - virtualmachineinstances
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - subresources.kubevirt.io
  resources:
  - virtualmachines/addvolume
  - virtualmachines/removevolume
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevirt-csi-infra-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubevirt-csi-infra-role
subjects:
- kind: ServiceAccount
  name: kubevirt-csi-infra-sa
  namespace: nested-cluster
